name: event_emitter
version: 0.2.0
homepage: https://github.com/clairesarsam-wf/dart-event-emitter
description:
  An extendable event emitter
authors:
  Joseph Moniz <joseph.moniz@gmail.com>
  Claire Sarsam <csarsam@gmail.com>