name: event_emitter
version: 0.1.1
homepage: https://github.com/JosephMoniz/dart-event-emitter
description: >
  An extendable event emitter
author: Joseph Moniz <joseph.moniz@gmail.com>
dependencies:
  dictionary: '>=0.2.0 <0.3.0'